version: "3.8"
services:
  mysqldb:
    image: mysql
    env_file: /.env
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    expose:
      - ${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/script
    networks:
      - default
  app:
    depends_on:
      - mysqldb
    build:
      dockerfile: Dockerfile
      context: /backend
    env_file: /.env
    #restart: on-failure
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&enabledTLSProtocols=TLSv1.2
      - spring.datasource.username=$MYSQLDB_USER
      - spring.datasource.password=$MYSQLDB_ROOT_PASSWORD
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.datasource.hikari.maximum-pool-size=10
      - spring.datasource.hikari.minimum-idle=2
      - spring.datasource.hikari.idle-timeout=30000
      - spring.datasource.hikari.connection-timeout=5000
      - spring.datasource.hikari.pool-name=myHikariPool
      - spring.datasource.hikari.username=$MYSQLDB_USER
      - spring.datasource.hikari.password=$MYSQLDB_ROOT_PASSWORD
      - spring.datasource.hikari.jdbc-url=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&enabledTLSProtocols=TLSv1.2
    networks:
      - default
    volumes:
     - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
networks:
  default:
    external: true
    name: banhang_default