version: "3.8"
services:
  mysql-container:
    container_name: mysql-container
    image: mysql
    env_file: /.env
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - ./sql/script.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - shoes-shop

  phpmyadmin-container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    env_file: /.env
    depends_on:
      - mysql-container
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    networks:
      - shoes-shop
    restart: unless-stopped
    ports:
      - ${PHP_LOCAL_PORT}:${PHP_DOCKER_PORT}

  shoes-shop-spring-container:
    container_name: shoes-shop-spring-container
    env_file: /.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: $MYSQLDB_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    networks:
      - shoes-shop
    restart: on-failure
    depends_on:
      - mysql-container
networks:
  shoes-shop:
    name: shoes-shop
    driver: bridge
    external: true