package com.ecomerce.roblnk.util;

public enum Status {

    DANG_CHO_XU_LY, // AWAITING PROCESSING
    DANG_XU_LY, // PROCESSING
    HOAN_TAT, //COMPLETED
    DA_GIAO_HANG, //SHIPPED
    DA_BI_HE_THONG_HUY,
    DA_BI_NGUOI_DUNG_HUY,
    DANG_VAN_CHUYEN,
    BI_TU_CHOI,
    DA_HOAN_TIEN,
    YEU_CAU_XAC_MINH_THU_CONG,
    CHO_GIAO_HANG
}
