application:
    jwt:
        expiration: 86400000 # a day
        refresh-token:
            expiration: 604800000 # 7 days
    secret-key: roblnkSecretKey1511ebcaccab1555cac46ca878eda68464dawd

server:
    port: 8081
spring:
    datasource:
        password: 123456
        url: jdbc:mysql://localhost:3306/e_commerce_shoes
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    mail:
        host: smtp.gmail.com
        password: LolaBaker15112002
        port: 420
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        protocol: smtps
        username: vunguyentrungkhang2@gmail.com
    security:
        filter:
            order: 0
        user:
            name: admin
            password: password
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2MB
            max-file-size: 5MB
            max-request-size: 10MB
